export const tipoMap: Record<string, string> = {
  creacion_usuario: 'Creacion Usuario',
  actualizacion_usuario: 'Actualizacion Usuario',
  eliminacion_usuario: 'Eliminacion Usuario',
  creacion_cliente: 'Creacion Cliente',
  actualizacion_cliente: 'Actualizacion Cliente',
  eliminacion_cliente: 'Eliminacion Cliente',
  creacion_producto: 'Creacion Producto',
  actualizacion_producto: 'Actualizacion Producto',
  actualizacion_precio_producto: 'Actualizacion Precio Producto',
  actualizacion_stock_producto: 'Actualizacion Stock Producto',
  eliminacion_producto: 'Eliminacion Producto',
  creacion_categoria: 'Creacion Categoria',
  actualizacion_categoria: 'Actualizacion Categoria',
  eliminacion_categoria: 'Eliminacion Categoria',
  creacion_proveedor: 'Creacion Proveedor',
  actualizacion_proveedor: 'Actualizacion Proveedor',
  eliminacion_proveedor: 'Eliminacion Proveedor',
  creacion_venta: 'Nueva Venta',
  eliminacion_venta: 'Cancelacion Venta',
  creacion_pago: 'Nuevo Pago',
  eliminacion_pago: 'Cancelacion Pago',
  apertura_caja: 'Apertura Caja',
  cierre_caja: 'Cierre Caja',
  registrar_transaccion: 'Nueva Transaccion',
  eliminar_caja: 'Eliminacion Caja',
  crear_synclog: 'Nuevo SyncLog',
  resolver_synclog: 'Resolucion SyncLog',
  eliminar_synclog: 'Eliminacion SyncLog',
};